- Ollivanders/src/net/pottercraft/Ollivanders2/House/O2Houses.java
- Ollivanders/src/net/pottercraft/Ollivanders2/O2Player.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Ollivanders2.java
- Ollivanders/src/net/pottercraft/Ollivanders2/OllivandersListener.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Spell/SpellProjectile.java
> Issue #109

- Ollivanders/src/net/pottercraft/Ollivanders2/Book/STANDARD_BOOK_OF_SPELLS_GRADE_6.java
> Added apparate to a book

- Ollivanders/src/net/pottercraft/Ollivanders2/O2Player.java
- Ollivanders/src/net/pottercraft/Ollivanders2/O2Players.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Ollivanders2.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Ollivanders2Common.java
- Ollivanders/src/net/pottercraft/Ollivanders2/OllivandersSchedule.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Spell/GEMINO.java
* renamed muggleton and related functions to make more clear
* moved logic for having invisibility cloak to OllivandersCommon
* serious changes to invisibility cloak   ( #10 ) and repello muggleton logic
* invisibility cloak seems to work fine now
* have not tested repello muggleton (muggle attribute created but not set and more work to do on spell outside of making players invisible)
> Iss10- Invisibility cloak works and changes to repello muggleton

- Ollivanders/src/net/pottercraft/Ollivanders2/Book/Book.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Book/O2Books.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Ollivanders2.java
* Fixed the give subCommand
* Noticed the list subCommand was not finished and implemented it too
> Issue 130 - /olli books give not working

- Ollivanders/src/net/pottercraft/Ollivanders2/O2Player.java
- Ollivanders/src/net/pottercraft/Ollivanders2/O2Players.java
I think I did everything :/
#132
> Added muggles

- Ollivanders/src/net/pottercraft/Ollivanders2/Spell/ALOHOMORA.java
- Ollivanders/src/net/pottercraft/Ollivanders2/StationarySpell/COLLOPORTUS.java
- Ollivanders/src/net/pottercraft/Ollivanders2/StationarySpell/StationarySpellObj.java
- Fixed Colloportus so that it checks if its duration has become <1 and kills itself
- Removed some unused and duplicate code in StationarySpellObj
- Cleaned up some unnecessary type declarations on Lists/Maps
https://github.com/Azami7/Ollivanders2/issues/140
> iss140 - Alohomora not canceling Colloportus

- Ollivanders/src/net/pottercraft/Ollivanders2/OLocation.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Ollivanders2Common.java
- Ollivanders/src/net/pottercraft/Ollivanders2/OllivandersListener.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Spell/CRESCERE_PROTEGAT.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Spell/ET_INTERFICIAM_ANIMAM_LIGAVERIS.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Spell/HORREAT_PROTEGAT.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Spell/INFORMOUS.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Spell/PARTIS_TEMPORUS.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Spell/PORTUS.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Spell/SpellProjectile.java
- Ollivanders/src/net/pottercraft/Ollivanders2/StationarySpell/ALIQUAM_FLOO.java
- Ollivanders/src/net/pottercraft/Ollivanders2/StationarySpell/ExtraDimensional.java
- Ollivanders/src/net/pottercraft/Ollivanders2/StationarySpell/HARMONIA_NECTERE_PASSUS.java
- Ollivanders/src/net/pottercraft/Ollivanders2/StationarySpell/HORCRUX.java
- Ollivanders/src/net/pottercraft/Ollivanders2/StationarySpell/O2StationarySpells.java
- Ollivanders/src/net/pottercraft/Ollivanders2/StationarySpell/PRAEPANDO.java
- Ollivanders/src/net/pottercraft/Ollivanders2/StationarySpell/PROTEGO.java
- Ollivanders/src/net/pottercraft/Ollivanders2/StationarySpell/PROTEGO_HORRIBILIS.java
- Ollivanders/src/net/pottercraft/Ollivanders2/StationarySpell/PROTEGO_MAXIMA.java
- Ollivanders/src/net/pottercraft/Ollivanders2/StationarySpell/PROTEGO_TOTALUM.java
- Ollivanders/src/net/pottercraft/Ollivanders2/StationarySpell/REPELLO_MUGGLETON.java
- Ollivanders/src/net/pottercraft/Ollivanders2/StationarySpell/StationarySpellObj.java
* Deprecated OLocation since it was only needed to serialize Locations and we use json now so we don't need this.
* Changed all use of OLocation to be Location
* Noticed some code duplication in functions that get nearby blocks/entities and refactored that
* Made some variable names clearer
* Fixed some imports
https://github.com/Azami7/Ollivanders2/issues/151
> Deprecated OLocation

- Ollivanders/src/net/pottercraft/Ollivanders2/Book/BookTexts.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Book/FOR_THE_GREATER_GOOD.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Book/O2Book.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Book/O2BookType.java
- Ollivanders/src/plugin.yml
* Added a new book for Morsmordre - For the Greater Good
* Also found a previous merge broke book text, fixed that
> Morsmordre not in any book

- Ollivanders/src/net/pottercraft/Ollivanders2/Book/BookTexts.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Ollivanders2Common.java
- Ollivanders/src/net/pottercraft/Ollivanders2/OllivandersListener.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Potion/ANIMAGUS_POTION.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Potion/ANTIDOTE_POTION.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Potion/BABBLING_BEVERAGE.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Potion/BARUFFIOS_BRAIN_ELIXIR.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Potion/FORGETFULLNESS_POTION.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Potion/HERBICIDE_POTION.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Potion/MEMORY_POTION.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Potion/O2Potion.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Potion/O2Potions.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Potion/REGENERATION_POTION.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Potion/WIT_SHARPENING_POTION.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Potion/WOLFSBANE_POTION.java
https://github.com/Azami7/Ollivanders2/issues/174
> Added libDisguises guards for potions

- Ollivanders/src/config.yml
- Ollivanders/src/net/pottercraft/Ollivanders2/House/O2HouseType.java
- Ollivanders/src/net/pottercraft/Ollivanders2/House/O2Houses.java
- Ollivanders/src/net/pottercraft/Ollivanders2/OllivandersListener.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Player/O2Player.java
https://github.com/Azami7/Ollivanders2/issues/200
> Added log in message

- Ollivanders/src/net/pottercraft/Ollivanders2/Potion/IngredientType.java
Added in some more ingredients :)
> New Potion Ingredients

- Ollivanders/src/net/pottercraft/Ollivanders2/OllivandersListener.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Potion/ANIMAGUS_POTION.java
Animagus potion - https://github.com/Azami7/Ollivanders2/pull/266
Mastered spell rotation - https://github.com/Azami7/Ollivanders2/pull/267
Fixes https://github.com/Azami7/Ollivanders2/issues/264
> Merge of bug fixes

- Ollivanders/src/config.yml
- Ollivanders/src/net/pottercraft/Ollivanders2/Divination/O2Divination.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Ollivanders2.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Spell/BAO_ZHONG_CHA.java
* Made divination max days configurable
* Made tasseomancy require facing a cauldron
* Made ovomancy consume the held egg
> A couple small tweaks for 2.2.9

- Ollivanders/src/net/pottercraft/Ollivanders2/GsonDAO.java
- Ollivanders/src/net/pottercraft/Ollivanders2/House/O2Houses.java
https://github.com/Azami7/Ollivanders2/issues/292
> Fixed NPE in reading json save files.

- Ollivanders/src/config.yml
- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2.java
- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2Common.java
- Ollivanders/src/net/pottercraft/ollivanders2/OllivandersListener.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/ANIMAGUS_EFFECT.java
- Ollivanders/src/net/pottercraft/ollivanders2/house/O2Houses.java
- Ollivanders/src/net/pottercraft/ollivanders2/item/O2ItemType.java
- Ollivanders/src/net/pottercraft/ollivanders2/player/O2Player.java
- Ollivanders/src/net/pottercraft/ollivanders2/player/O2PlayerCommon.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/ALIQUAM_FLOO.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/EntityTransfiguration.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/HARMONIA_NECTERE_PASSUS.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/O2Spell.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/HARMONIA_NECTERE_PASSUS.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/StationarySpellObj.java
- Ollivanders/src/plugin.yml
First pass at 1.14.4 support:
* removed MC < 12 code since other changes to make 1.14.4 compile cannot run in lower versions
* fixes to make 1.14.4 compile
* added config to allow overriding the MC version check for server owners who want to run on unsupported versions
* added banner message for sorting
* added additional creature types to various places that use them
> Initial 1.14.4 support

- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2API.java
- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2Common.java
- Ollivanders/src/net/pottercraft/ollivanders2/OllivandersListener.java
- Ollivanders/src/net/pottercraft/ollivanders2/item/O2ItemType.java
- Ollivanders/src/net/pottercraft/ollivanders2/player/O2Player.java
- Ollivanders/src/net/pottercraft/ollivanders2/player/O2PlayerCommon.java
- Ollivanders/src/net/pottercraft/ollivanders2/player/O2WandCoreType.java
- Ollivanders/src/net/pottercraft/ollivanders2/player/O2WandWoodType.java
- Ollivanders/src/net/pottercraft/ollivanders2/player/events/OllivandersPlayerNotDestinedWandEvent.java
- fixed knut material
- added new event fired when players try a wand that isnt their destined wand
- changed player wand wood/core accessors so they dont return null
- made wandLoreConjunction public for use elsewhere
- added a get random type for O2WandCoreType and O2WandWoodType
- changed OllivandersAPI to only make objects if they are not initialized... derp
> Updates for pottercraft

- Ollivanders/src/config.yml
- Ollivanders/src/net/pottercraft/ollivanders2/GsonDAO.java
- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2.java
- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2Common.java
- Ollivanders/src/net/pottercraft/ollivanders2/OllivandersSchedule.java
https://github.com/Azami7/Ollivanders2/issues/303
- added support for hourly backups, config driven
- added config for archiving (which it did by default previously)
- fixed debug messages in updated code to use printDebugMessage()
- added comments to OllivandersSechedule and renamed timer variable
> Periodic backups

- Ollivanders/src/config.yml
- Ollivanders/src/net/pottercraft/ollivanders2/GsonDAO.java
- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2.java
- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2Common.java
- Ollivanders/src/net/pottercraft/ollivanders2/OllivandersSchedule.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/O2Spell.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/REDUCTO.java
- cannot be enabled when bookLearning is on
- overrides spell usage to 200 which should max the power for any spell
https://github.com/Azami7/Ollivanders2/issues/364
> Support for setting spell power to max

- Ollivanders/src/config.yml
- Ollivanders/src/net/pottercraft/ollivanders2/GsonDAO.java
- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2.java
- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2Common.java
- Ollivanders/src/net/pottercraft/ollivanders2/OllivandersSchedule.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/O2Spell.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/REDUCTO.java
- Ollivanders/src/plugin.yml
Allow version 2.6 to run on MC 1.17.
Testing:
MC 1.17 with no plugins
MC 1.17 with WorldGuard
Open Issues:
ProtocolLib has not been updated to support 1.17 so all Transfiguration that requires LibsDisguises will not work.
> 1.17 support

- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2.java
Added checks to plugin commands where the CommandSender must be a Player to prevent the command from trying to run if the sender isn't a player.
https://github.com/Azami7/Ollivanders2/issues/389
> Sender instance of player checks

- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2.java
- give book to player was still checking if the command sender was a player but this is not needed for this command
- give book to player was missing the actual give the book part... hmmm
https://github.com/Azami7/Ollivanders2/issues/389
> Fixed give book to player

- Ollivanders/src/net/pottercraft/ollivanders2/book/O2Books.java
- moved functionality to Pottercraft, not generic feature
> Hogwarts Library

- Ollivanders/src/net/pottercraft/ollivanders2/spell/APPARATE.java
- added maxApparateDistance config
- fixed an incomplete javadoc comment on getDestination()
- removed unnecessary type cast in ArrayList declaration
> Apparate Distance Limits

- Ollivanders/src/net/pottercraft/ollivanders2/potion/O2Potion.java
- Make potion brewing also respect maxSpellLevel config
- moved Year modifiers in to if years enabled block
> Updated to canBrew()

- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/FLYING.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/O2Effects.java
- Ollivanders/src/net/pottercraft/ollivanders2/player/O2Players.java
- Ollivanders/src/plugin.yml
Add command to set animagus for a player
- added animagus command
- moved player-related command summary and year to O2Players
Add permissions support for Ollivanders
- added Ollivanders.admin permission for all commands
> Animagus command and permissions

- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2.java
- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2API.java
- Ollivanders/src/net/pottercraft/ollivanders2/house/O2HouseType.java
- Ollivanders/src/net/pottercraft/ollivanders2/house/O2Houses.java
- fixed bug where the check on usehouses was flipped in scoreboard set up - duh
- made handling invalid house color more graceful
> House config bug

- Ollivanders/src/net/pottercraft/ollivanders2/common/Ollivanders2Common.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/LUMOS_SOLEM.java
- projectile was not moving forward due to bad check
- made a flair at the target so the player can see it was cast
- added a new flair function to set the effect type
- added radius to the spell
> Lumos Solem

- Ollivanders/src/config.yml
- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2.java
- Ollivanders/src/net/pottercraft/ollivanders2/common/Ollivanders2Common.java
- Ollivanders/src/net/pottercraft/ollivanders2/listeners/OllivandersListener.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/DEPULSO.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/FLIPENDO.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/FriendlyMobDisguise.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/Knockback.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/REPARO.java
- added config to set faster spell casting since it was causing performance issues on at least one server
- changed knockback WG checks to be more precise
- renamed friendly animals list to friendly mobs since some are not Animals
- fixed flipendo text to be more accurate
- added message in REPARO when user successfully repairs so they know it worked
> Spell performance issues

- Ollivanders/src/net/pottercraft/ollivanders2/effect/SLEEPING.java
- actually added the immobilize effect
- added message to target when they are affected
> Sleep effect not immobilizing player

- Ollivanders/src/net/pottercraft/ollivanders2/spell/AQUA_ERUCTO.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/O2Spell.java
- removed Fire from the pass through blocks
> Aqua Eructo not targeting fire blocks

- Ollivanders/src/net/pottercraft/ollivanders2/potion/FORGETFULLNESS_POTION.java
- Ollivanders/src/net/pottercraft/ollivanders2/potion/WIT_SHARPENING_POTION.java
- was not decrementing skill level properly
> Forgetfulness Potion fix

- Ollivanders/src/config.yml
- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2.java
- Ollivanders/src/net/pottercraft/ollivanders2/potion/ANIMAGUS_POTION.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/AMATO_ANIMO_ANIMATO_ANIMAGUS.java
- Add config for using strict animagus conditions or not
> Config for strict animagus conditions

- Ollivanders/src/net/pottercraft/ollivanders2/spell/ALIQUAM_FLOO.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/ALIQUAM_FLOO.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/O2StationarySpell.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/O2StationarySpells.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/events/FlooNetworkEvent.java
https://github.com/Azami7/Ollivanders2/issues/485
- added FlooNetworkEvent
- refactored floo network code
- change floo network effect to continue while fireplace active
- added player message when travel request succeeds or fails (if event is canceled)
- increased radius for combustion protection so players do not walk away on fire
> Floo refactor and FlooNetworkEvent

- Ollivanders/src/net/pottercraft/ollivanders2/house/O2Houses.java
- Ollivanders/src/net/pottercraft/ollivanders2/player/O2Player.java
- Ollivanders/src/plugin.yml
- throw player sorted event on sort
- fixing plugin version which was incorrectly updated on a merge
> Player Sorted Event

- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/REPELLO_MUGGLETON.java
- Ollivanders/src/plugin.yml
updated repello muggleton to not use deprecated Block.gerData()
> Repello muggleton

- Ollivanders/src/config.yml
- Ollivanders/src/net/pottercraft/ollivanders2/item/O2Items.java
- Ollivanders/src/net/pottercraft/ollivanders2/item/enchantment/PORTUS.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/ALIQUAM_FLOO.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/HARMONIA_NECTERE_PASSUS.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/ALIQUAM_FLOO.java
- Ollivanders/src/plugin.yml
- made a floo section in config
- added config for soulfire floo 
- logic to change the fire to soul fire when the floo is active
- added sort to item list because it was messy to read without it
- fixed use of deprecated sign getLine() 
- moved common code in aliquam floo constructors to a shared init() function
misc
- also fixed warning for use of deprecated getBedSpawnLocation()
> Aliquam floo soul fire

- Ollivanders/src/net/pottercraft/ollivanders2/spell/LEPUS_SACCULUM.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/O2SpellType.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/RANACULUS_AMPHORAM.java
- added lepus sacculum which turns rabbits in to bundles
- lowered radius on other two entity to item spells to 1.5, 3 was used for testing
https://github.com/Azami7/Ollivanders2/issues/551
> Mice to snuffboxes

- Ollivanders/src/net/pottercraft/ollivanders2/book/QUINTESSENCE_A_QUEST.java
- Ollivanders/src/net/pottercraft/ollivanders2/book/STANDARD_BOOK_OF_SPELLS_GRADE_2.java
- Ollivanders/src/net/pottercraft/ollivanders2/item/enchantment/CELATUM.java
- Ollivanders/src/net/pottercraft/ollivanders2/item/enchantment/EnchantedItems.java
- Ollivanders/src/net/pottercraft/ollivanders2/item/enchantment/FLAGRANTE.java
- Ollivanders/src/net/pottercraft/ollivanders2/item/enchantment/GEMINIO.java
- Ollivanders/src/net/pottercraft/ollivanders2/item/enchantment/ItemEnchantmentType.java
- Ollivanders/src/net/pottercraft/ollivanders2/item/enchantment/PORTUS.java
- Ollivanders/src/net/pottercraft/ollivanders2/item/enchantment/VOLATUS.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/ABERTO.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/ALOHOMORA.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/APARECIUM.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/CELATUM.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/FLAGRANTE.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/GEMINIO.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/ItemEnchant.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/O2SpellType.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/PORTUS.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/VOLATUS.java
- added new spell celatus that hides the text in a boo 
- refactored aparecium to match canon and reveal hidden text
- added links in javadoc on all enchantments and item enchant spells
https://github.com/Azami7/Ollivanders2/issues/563
> Aparecium and Celatus

- Ollivanders/src/net/pottercraft/ollivanders2/book/STANDARD_BOOK_OF_SPELLS_GRADE_2.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/DANCING_FEET.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/O2Effect.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/O2EffectType.java
- Ollivanders/src/net/pottercraft/ollivanders2/potion/O2Potions.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/O2SpellType.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/SKURGE.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/TARANTALLEGRA.java
- added the charm Tarantallegra
- added the effect dancing_feet
- javadoc & code cleanup
https://github.com/Azami7/Ollivanders2/issues/77
> Tarantallegra

- Ollivanders/src/net/pottercraft/ollivanders2/book/BASIC_HEXES.java
- Ollivanders/src/net/pottercraft/ollivanders2/book/STANDARD_BOOK_OF_SPELLS_GRADE_2.java
- Ollivanders/src/net/pottercraft/ollivanders2/divination/O2Divination.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/AGGRESSION.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/BABBLING.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/DANCING_FEET.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/HUNGER.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/LAUGHING.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/LUCK.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/MUTED_SPEECH.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/O2Effect.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/O2EffectType.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/O2Effects.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/SLOWNESS.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/TICKLING.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/UNLUCK.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/WEAKNESS.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/AddO2Effect.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/EBUBLIO.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/FUMOS.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/FUMOS_DUO.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/IMPEDIMENTA.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/LEVICORPUS.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/LOQUELA_INEPTIAS.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/MUCUS_AD_NAUSEAM.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/O2SpellType.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/RICTUSEMPRA.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/TARANTALLEGRA.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/TITILLANDO.java
- added the charm rictusempra
- added the hex titillando
- updated all effects to have an optional message to the affected player when the effect is added
https://github.com/Azami7/Ollivanders2/issues/78
https://github.com/Azami7/Ollivanders2/issues/92
> Rictusempra and Titillando

- Ollivanders/src/net/pottercraft/ollivanders2/book/ADVANCED_POTION_MAKING.java
- Ollivanders/src/net/pottercraft/ollivanders2/book/MAGICAL_DRAFTS_AND_POTIONS.java
- Ollivanders/src/net/pottercraft/ollivanders2/item/O2ItemType.java
- Ollivanders/src/net/pottercraft/ollivanders2/potion/CURE_FOR_BOILS.java
- Ollivanders/src/net/pottercraft/ollivanders2/potion/ICE_POTION.java
- Ollivanders/src/net/pottercraft/ollivanders2/potion/O2PotionType.java
- Ollivanders/src/net/pottercraft/ollivanders2/potion/OCULUS_FELIS.java
- Ollivanders/src/net/pottercraft/ollivanders2/potion/STRENGTHENING_SOLUTION.java
- added strengtening solution
- adjusted some potion effect intensities
https://github.com/Azami7/Ollivanders2/issues/587
> Strengthening Solution

- Ollivanders/src/net/pottercraft/ollivanders2/book/MAGICAL_DRAFTS_AND_POTIONS.java
- Ollivanders/src/net/pottercraft/ollivanders2/item/O2ItemType.java
- Ollivanders/src/net/pottercraft/ollivanders2/potion/O2PotionType.java
- Ollivanders/src/net/pottercraft/ollivanders2/potion/WEAKNESS_POTION.java
- added weakness potion
https://github.com/Azami7/Ollivanders2/issues/589
> Weakness potion

- Ollivanders/src/net/pottercraft/ollivanders2/book/MAGICAL_DRAFTS_AND_POTIONS.java
- Ollivanders/src/net/pottercraft/ollivanders2/divination/O2Divination.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/O2EffectType.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/PlayerChangeSizeSuper.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/SHRINKING.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/SWELLING.java
- Ollivanders/src/net/pottercraft/ollivanders2/item/O2ItemType.java
- Ollivanders/src/net/pottercraft/ollivanders2/potion/HERBICIDE_POTION.java
- Ollivanders/src/net/pottercraft/ollivanders2/potion/O2PotionType.java
- Ollivanders/src/net/pottercraft/ollivanders2/potion/SHRINKING_SOLUTION.java
- Ollivanders/src/net/pottercraft/ollivanders2/potion/SWELLING_SOLUTION.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/ChangeEntitySizeSuper.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/ENGORGIO.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/O2Spell.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/REDUCIO.java
- added shrinking and swelling potions
- added shrinking and swelling player wffects
- added a base effect class for any player scale changes
- improved logic in O2Spell for checking world guard entity damage
- added todo on herbicide potion
https://github.com/Azami7/Ollivanders2/issues/593
https://github.com/Azami7/Ollivanders2/issues/493
> Shrinking and swelling solutions
