Azami7/Ollivanders2

- Ollivanders/src/net/pottercraft/Ollivanders2/Spell/GaleatiSuper.java
Turns out if you tell it there are 0 items in the stack, there are 0 items in the stack.
> Fixed setHelmet

- Ollivanders/src/net/pottercraft/Ollivanders2/O2Player.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Ollivanders2.java
- Ollivanders/src/net/pottercraft/Ollivanders2/OllivandersListener.java
Changed how we rotate through spells so that, rather than sneak-click, holding the wand in the off hand and right or left clicking rotates through. This keeps wand in primary hand actions consistent as always resulting in a magical action/effect happening.  
Refactored onPlayerInteract() in to helper functions since it was getting unruly.
> Iss122 - fix rotating through mastered spells

- Ollivanders/src/net/pottercraft/Ollivanders2/Book/MAGICAL_DRAFTS_AND_POTIONS.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Book/O2Books.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Book/THE_HEALERS_HELPMATE.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Effect/LYCANTHROPY.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Effect/O2Effects.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Effect/ShapeShiftSuper.java
- Ollivanders/src/net/pottercraft/Ollivanders2/GsonDataPersistenceLayer.java
- Ollivanders/src/net/pottercraft/Ollivanders2/House/O2HouseType.java
- Ollivanders/src/net/pottercraft/Ollivanders2/House/O2Houses.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Ollivanders2.java
- Ollivanders/src/net/pottercraft/Ollivanders2/OllivandersListener.java
- Ollivanders/src/net/pottercraft/Ollivanders2/OllivandersSchedule.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Player/O2Players.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Potion/ANIMAGUS_POTION.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Potion/COMMON_ANTIDOTE_POTION.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Potion/O2PotionType.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Potion/O2Potions.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Spell/AMATO_ANIMO_ANIMATO_ANIMAGUS.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Spell/ET_INTERFICIAM_ANIMAM_LIGAVERIS.java
- Ollivanders/src/net/pottercraft/Ollivanders2/Spell/LEGILIMENS.java
Added saving potions and reading potion experience to player file
Fixed race condition in re-adding effects on Join
Added protections for NPEs in a few places
Added logic to protect clobbering save files with bad saves and archive previous versions rather than overwrite
Fixed unnecessary double loops in OllivandersSchedule
Fixed name of antidote potion class and enum
> Potions part 2 - saving experience between restarts

- Ollivanders/src/net/pottercraft/ollivanders2/O2Color.java
- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2API.java
- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2Common.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/ANIMAGUS_EFFECT.java
- Ollivanders/src/net/pottercraft/ollivanders2/player/O2Player.java
- Ollivanders/src/net/pottercraft/ollivanders2/player/O2PlayerCommon.java
- Ollivanders/src/net/pottercraft/ollivanders2/player/O2Players.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/AVIFORS.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/AVIS.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/EQUUSIFORS.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/INCARNATIO_DEVITO.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/INCARNATIO_EQUUS.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/INCARNATIO_FELIS.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/INCARNATIO_LAMA.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/INCARNATIO_URSUS.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/INCARNATIO_VACCULA.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/LAPIFORS.java
* Added additional entity-specific watchers
* Added new mob types for existing LibsDisguises spells
* Fixed where Ocelots were being used for Cats since these are split out in 1.14
* Added logic to seed entity colors/types by uuid so they are always the same for any player
* Added a fix() function to use for cleanup of player data from earlier plugin versions
* Added "rare" animagus forms to make less common animals less common forms
* Removed unused plugin callback from O2PlayerCommon
> Updated to use LibsDisguises 9.9 for 1.14 support

- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2.java
- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2Common.java
- Ollivanders/src/net/pottercraft/ollivanders2/book/O2BookType.java
- Ollivanders/src/net/pottercraft/ollivanders2/house/O2Houses.java
- Ollivanders/src/net/pottercraft/ollivanders2/house/events/OllivandersPlayerSortedEvent.java
- Ollivanders/src/net/pottercraft/ollivanders2/player/events/OllivandersPlayerFoundWandEvent.java
Minor tweaks needed for pottercraft plugin mechanics but will also be useful to other server customizations.
- added accessor for book short title
- added some NotNull/Nullable contracts
- updated text on player summary command to be more generic
- updated item comparison function to handle written books special case
Tested locally and on Pottercraft-Test
> Minor tweaks to books and player summary command

- Ollivanders/src/net/pottercraft/ollivanders2/effect/O2Effect.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/O2Effects.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/MetelojinxSuper.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/REPARO.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/StationarySpellObj.java
- reparo was not properly setting the updated damage
- reparo was reparing the item twice because the repaired item was being picked up in the iterating loop
- use of -= not correct
> Reparo fix

- Ollivanders/src/net/pottercraft/ollivanders2/OllivandersSchedule.java
Fixed bug where a geminio item with malformed lore can cause an ArrayIndexOutOfBoundsException
> Geminio ArrayIndexOutOfBoundsException

- Ollivanders/src/config.yml
- Ollivanders/src/net/pottercraft/ollivanders2/GsonDAO.java
- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2.java
- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2API.java
- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2WorldGuard.java
- Ollivanders/src/net/pottercraft/ollivanders2/OllivandersListener.java
- Ollivanders/src/net/pottercraft/ollivanders2/divination/O2Prophecies.java
- Ollivanders/src/net/pottercraft/ollivanders2/house/O2Houses.java
- Ollivanders/src/net/pottercraft/ollivanders2/player/O2Players.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/APPARATE.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/O2Spell.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/O2StationarySpells.java
Added support for apparating by named location rather than by coordinate. When enabled, coordinates cannot be used. Locations are persisted to the plugin directory.
- refactored apparate entirely - it was implemented twice (once in spell, once in OllivandersListener, no idea why, way over-complicated and the implementations didn't even match :/
- added support for named apparate locations
- added isWandless flag to spells so we dont have to remember to override the rightWand arg in constructors
- fixed usage messages - commands missing, some had no usage messages
- fixed really bad bug in WG state check where it was sending back the opposite result of what we want - yikes
- fixed debug messages to use printDebugMessage
- removed plugin param to GsonDAO constructor since we don't really …
> Apparate locations

- Ollivanders/src/README.md
- Ollivanders/src/config.yml
- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2.java
- Ollivanders/src/net/pottercraft/ollivanders2/book/O2Books.java
- Ollivanders/src/net/pottercraft/ollivanders2/item/O2ItemType.java
- Ollivanders/src/net/pottercraft/ollivanders2/item/O2Items.java
- Ollivanders/src/net/pottercraft/ollivanders2/item/enchantment/EnchantedItems.java
- Ollivanders/src/net/pottercraft/ollivanders2/item/enchantment/VOLATUS.java
- added enableBrooms, default set to true
- added item enchantments for O2ItemType since broomsticks were no longer by default flyable
- added support for setting item enchantments by ItemStack in addition to Item
- turned off writing config if the file exists since when it writes back out it loses all the helpful comments
- marked readLore as deprecated so we remember to clean it up in a few versions
- cleaned up unused zone config from Ollivanders2 (it was moved to O2Spells)
> Add broom enable/disable config

- Ollivanders/src/net/pottercraft/ollivanders2/book/O2BookType.java
- Ollivanders/src/net/pottercraft/ollivanders2/book/O2Books.java
- Practical Defensive Magic Volume One title was too long, breaking book, shortened
- Added code to truncate O2Book short titles if they exceed 32 characters
- also fixed bug where readLore was using title rather than shortTitle to compare to book meta title
> Invalid book tag

- Ollivanders/src/net/pottercraft/ollivanders2/item/O2ItemType.java
- melon stem item used seems to be gone in 1.16, changed to kelp
> /olli item is not giving mint sprigs

- Ollivanders/src/config.yml
- Ollivanders/src/net/pottercraft/ollivanders2/common/Ollivanders2Common.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/O2Spell.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/PACK.java
- added a getItemsInRadius common function
- added material allow list to O2Spell which takes precedence over the deny list
- small refactor of checkEffect(), move(), and checkTarget() in O2Spell to clean up logic
- refactored pack code to be clearer
- changed to only work with "magic" chests - ender chests and shulker boxes
> Pack not packing

- Ollivanders/src/config.yml
- Ollivanders/src/net/pottercraft/ollivanders2/common/Ollivanders2Common.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/AddPotionEffect.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/AddPotionEffectInRadius.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/CONFUNDO.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/CONFUNDUS_DUO.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/ConfundusSuper.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/EPISKEY.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/FUMOS.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/FUMOS_DUO.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/FumosSuper.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/IMMOBULUS.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/IMPEDIMENTA.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/LUMOS.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/O2Spell.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/OBSCURO.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/PACK.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/STUPEFY.java
- refactored how the amplifier on potion effects works
- AddPotionEffect was targeting the caster - fixed so that would only happen if the spell is self-targeting
- fixed AddPotionEffect to target LivingEntity not just Player
- moved amplifier and duration checks to doInitSpell()
- cleaned up checkEffect() for AddPotionEffectInRadius
- updated text for IMPEDIMENTA
> Impedimeta not working

- Ollivanders/src/net/pottercraft/ollivanders2/book/O2Book.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/LUMOS.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/NOX.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/RemovePotionEffect.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/RemovePotionEffectInRadius.java
- decreased line size to prevent cutting off the ingredients lists for potions
- NOX was not targeting self (feel like we fixed this before...) because RemovePotionEffectInRadius incorrectly overwrote the targetSelf class variable
- Gave lumos and nox varing radius by spell skill level
> Potions Texts, Lumos and Nox fixes

- Ollivanders/src/config.yml
- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2.java
- Ollivanders/src/net/pottercraft/ollivanders2/item/O2ItemType.java
- Ollivanders/src/net/pottercraft/ollivanders2/listeners/OllivandersListener.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/O2Spells.java
- Ollivanders/src/plugin.yml
- Changed item give command to take in an amount
- Decreased default thread delay to 0.5 seconds
- zone config is read before spells are loaded so none are added to the config
- updated mcVersionCheck to support 1.18 and remove 1.16 support
> Zone config, item amount, mcVersionCheck fix

- Ollivanders/src/net/pottercraft/ollivanders2/common/Ollivanders2Common.java
- Ollivanders/src/net/pottercraft/ollivanders2/listeners/OllivandersListener.java
- Ollivanders/src/net/pottercraft/ollivanders2/potion/O2Potions.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/HERBIVICUS.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/OVOGNOSIS.java
- updated potion brewing to handle new 1.17 WATER_CAULDRON material
- minor code formatting clean up
- added explicit removal of empty bottle from player's hand since it seems 1.17 was not doing that but putting the potion in the inv when the hand is already full
- removed unused crop state list from Herbivicus (leftover from pre 1.14 API upgrade I think)
- faced same cauldron issue with Ovognosis
> https://github.com/Azami7/Ollivanders2/issues/494

- Ollivanders/src/net/pottercraft/ollivanders2/Ollivanders2.java
- Ollivanders/src/plugin.yml
We can rely on the built-in MC api-version check (from plugin.yml). Also fixed MC version in mainline back to 2.7.
> Remove mcVersionCheck

- Ollivanders/src/net/pottercraft/ollivanders2/OllivandersSchedule.java
- Ollivanders/src/net/pottercraft/ollivanders2/common/Ollivanders2Common.java
- Ollivanders/src/net/pottercraft/ollivanders2/listeners/OllivandersListener.java
- Ollivanders/src/net/pottercraft/ollivanders2/player/O2Player.java
- Ollivanders/src/net/pottercraft/ollivanders2/player/O2PlayerCommon.java
- Ollivanders/src/net/pottercraft/ollivanders2/player/O2Players.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/O2Spell.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/StationarySpell.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/ALIQUAM_FLOO.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/COLLOPORTUS.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/HARMONIA_NECTERE_PASSUS.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/HORCRUX.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/MOLLIARE.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/MUFFLIATO.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/NULLUM_APPAREBIT.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/NULLUM_EVANESCUNT.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/O2StationarySpell.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/O2StationarySpells.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/PROTEGO.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/PROTEGO_HORRIBILIS.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/PROTEGO_MAXIMA.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/PROTEGO_TOTALUM.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/REPELLO_MUGGLETON.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/ShieldSpell.java
- refactored invis schedule to just handle invisibility cloaks
- cleaned up how invis is handled, which was unnecessary complicated
- moved handling visiblity for repello muggleton in to the stationary spell with listeners
- added chat blocking for repello muggleton
- added preventing muggles entering the area
- clean up on the O2Player muggle code which I am pretty sure was not working
- added a better constructor for stationary spells
- added a cleanup method for stationary spells
- fixed bug in how the block allow list was being checked for spells
- added handling for null in flair since sometimes it happens
https://github.com/Azami7/Ollivanders2/issues/132
> todo cleanup on invisPlayer() and update Repello Muggleton

- Ollivanders/src/net/pottercraft/ollivanders2/spell/ET_INTERFICIAM_ANIMAM_LIGAVERIS.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/ItemEnchant.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/HORCRUX.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/O2StationarySpell.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/O2StationarySpells.java
- changed horcrux preserve the item in the location (no despawn)
- restore item on restart
- do not allow item pick up because if a player picks it up and moves it the spell location wont be right anymore
- on player death, preserve inventory, experience, level
- only allow 1 horcrux at a time
- fixed a duplicate isEnchanted check in ItemEnchant
https://github.com/Azami7/Ollivanders2/issues/183
> Horcrux rewrite

- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/HORCRUX.java
fix to handle item despawn events happening at server start before the stationary spells have been completely set up
> horcrux start up fix

- Ollivanders/src/config.yml
- Ollivanders/src/net/pottercraft/ollivanders2/common/Ollivanders2Common.java
- Ollivanders/src/net/pottercraft/ollivanders2/effect/PROTEGO.java
- Ollivanders/src/net/pottercraft/ollivanders2/item/wand/O2WandCoreType.java
- Ollivanders/src/net/pottercraft/ollivanders2/listeners/OllivandersListener.java
- Ollivanders/src/net/pottercraft/ollivanders2/potion/HERBICIDE_POTION.java
- Ollivanders/src/net/pottercraft/ollivanders2/potion/O2Potion.java
- Ollivanders/src/net/pottercraft/ollivanders2/potion/O2SplashPotion.java
- Ollivanders/src/net/pottercraft/ollivanders2/potion/WIGGENWELD_POTION.java
- Ollivanders/src/net/pottercraft/ollivanders2/spell/HERBIVICUS.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/HERBICIDE.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/O2StationarySpellType.java
- Ollivanders/src/net/pottercraft/ollivanders2/stationaryspell/ThrownPotionStationarySpell.java
Herbicide rework
- added to herbicide affecting plant blocks in the area of the thrown potion
- added new stationary spell type for affecting an area from a potion splash
- updated plugin to MC 1.21.7
https://github.com/Azami7/Ollivanders2/issues/595
> Herbicide rework
